spring:
  application:
    name: fw-payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:finalwork@localhost:8761/eureka/
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
  password: ${USER_PASSWORD:password}


server:
  error:
    include-message: always
  port: 8888