server:
  error:
    include-message: always
  port: 8888

spring:
  application:
    name: fw-payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: https://fw-discovery-server.azurewebsites.net/eureka
  instance:
    hostname: fw-payment-service.azurewebsites.net
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}

stripe:
  secretKey: 'sk_test_51L2waTAKK7UhTIYhWZ0gap86miBgGOg7GX8NTKVum9cSyUdceoKrjFgrWhvAjBwVDQXz1wVq5aw6vCkyOOwSpBAS003FVAjo7e'
  secretWebHook: 'whsec_Q1fU0hovc7yvPyM92XfOx062egs3XQl9'
  #secretWebHook: 'whsec_bXrcq5bE3eD520p55jUEmo63Qkiuegu9'

app:
  services:
    partnership:
      url: https://fw-partnership-service.azurewebsites.net